# stack.yaml docs:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

user-message: ! 'Warning (added by new or init): Specified resolver could not satisfy
  all dependencies. Some external packages have been added as dependencies.

  You can suppress this message by removing it from stack.yaml

'

# resolver: nightly-2015-09-21
# resolver: ghc-7.10.2
resolver: lts-9.0

packages:
- .

extra-deps:
- leancheck-0.6.4
- speculate-0.2.8

flags: {}

extra-package-dbs: []
